// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-24T19:24:27+03:00
// RPL version: 0.7.3
// Author: <rpl>
package plugins

import (
	sqlplugin "github.com/caramelang/caramel/internal/models/sql_plugin"
)

// Plugins описывает сгенерированную модель данных.
type Plugins struct {
	Plugins []sqlplugin.SqlPlugin
}
