// Code generated by RPL. DO NOT EDIT.
// Generated at: 2026-07-24T19:24:27+03:00
// RPL version: 0.7.3
// Author: <rpl>
package position

// Position описывает сгенерированную модель данных.
type Position struct {
	FileName string
	Start    uint64
	End      uint64
}
